commenting out tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -83,30 +83,30 @@ jobs:
           tflint --version
           pre-commit run --all-files
 
-  test:
-    name: test
-    runs-on: ubuntu-latest
+  # test:
+  #   name: tests
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
 
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.9'
-          cache: 'pip'
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.9'
+  #         cache: 'pip'
 
-      - name: Install Python packages
-        run: pip install -r requirements.txt
+  #     - name: Install Python packages
+  #       run: pip install -r requirements.txt
 
-      - name: Test with pytest
-        run: |
-          pytest --junitxml=test-results.xml
-        working-directory: ./tests
+  #     - name: Test with pytest
+  #       run: |
+  #         pytest --junitxml=test-results.xml
+  #       working-directory: ./tests
 
-      - uses: actions/upload-artifact@v2
-        if: success() || failure()
-        with:
-          name: test-results
-          path: test-results.xml
+  #     - uses: actions/upload-artifact@v2
+  #       if: success() || failure()
+  #       with:
+  #         name: test-results
+  #         path: test-results.xml
